# 什么是Pytorch
基于Python提供GPU的Numpy功能，深度学习研究平台，提供了更高的灵活性的速度。

# 开始

### Tensors

tensors与numpy数组类似，提供了GPU端计算的能力。

In [1]:
from __future__ import print_function
import torch

构建5x3的矩阵

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.1704e-41],
        [ 0.0000e+00,  2.2369e+08,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [        nan,         nan, -2.5376e-19]])


构建随机初始化矩阵

In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.5170, 0.8655, 0.0027],
        [0.1411, 0.7976, 0.7315],
        [0.1867, 0.7522, 0.5650],
        [0.3164, 0.8382, 0.3060],
        [0.8722, 0.3841, 0.7340]])


构建使用long类型的0进行填充的矩阵

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接基于数据构建矩阵

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


基于现有的tensor创建，

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3970,  0.2476, -0.6414],
        [ 0.5256,  1.4046, -0.0773],
        [-0.1294,  1.0121, -1.1236],
        [ 0.1314,  0.2712, -0.0701],
        [-1.0487,  0.0035,  0.0869]])


In [7]:
# 获取大小
print(x.size())

torch.Size([5, 3])


# 操作

In [9]:
# 加法
y = torch.rand(5, 3)
print(y)
x = torch.ones(5, 3)
print(x + y)

tensor([[0.6598, 0.3690, 0.3459],
        [0.0368, 0.3244, 0.2354],
        [0.6486, 0.1451, 0.5632],
        [0.9037, 0.0752, 0.6917],
        [0.5040, 0.6243, 0.4119]])
tensor([[1.6598, 1.3690, 1.3459],
        [1.0368, 1.3244, 1.2354],
        [1.6486, 1.1451, 1.5632],
        [1.9037, 1.0752, 1.6917],
        [1.5040, 1.6243, 1.4119]])


In [10]:
y = torch.rand(5, 3)
print(torch.add(x, y))

tensor([[1.0696, 1.4733, 1.2029],
        [1.0286, 1.8040, 1.3675],
        [1.8256, 1.5881, 1.1966],
        [1.5970, 1.2297, 1.2766],
        [1.3124, 1.8123, 1.2981]])


In [12]:
# 指定输出
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0696, 1.4733, 1.2029],
        [1.0286, 1.8040, 1.3675],
        [1.8256, 1.5881, 1.1966],
        [1.5970, 1.2297, 1.2766],
        [1.3124, 1.8123, 1.2981]])


In [13]:
# 累加替换
y.add_(x)
print(y)

tensor([[1.0696, 1.4733, 1.2029],
        [1.0286, 1.8040, 1.3675],
        [1.8256, 1.5881, 1.1966],
        [1.5970, 1.2297, 1.2766],
        [1.3124, 1.8123, 1.2981]])


In [14]:
# 类似numpy选择
print(x[:1])

tensor([[1., 1., 1.]])


In [15]:
# 变形
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
# 使用item获取值
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2794])
0.27939271926879883


# Numpy